CREATE TABLE `blogarticle` (
  `blogID` int(5) NOT NULL AUTO_INCREMENT,
  `articletitle` varchar(40) DEFAULT NULL,
  `articletext` text,
  `blogtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `blogposter` int(5) DEFAULT NULL,
  PRIMARY KEY (`blogID`),
  KEY `blogposter` (`blogposter`),
  CONSTRAINT `blogarticle_ibfk_1` FOREIGN KEY (`blogposter`) REFERENCES `usertable` (`userid`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `blogarticle` (`blogID`,`articletitle`,`articletext`,`blogtime`,`blogposter`) VALUES (1,'Article Entry Number 1 Heading','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla congue a urna nec pharetra. Maecenas et felis ipsum. Donec mattis lacus orci, quis hendrerit nibh blandit at. Donec viverra pulvinar risus, sed auctor nulla luctus vel. Quisque iaculis id mauris eget condimentum. Integer commodo turpis nibh, eget mattis libero hendrerit id. Vestibulum nec faucibus est. Nulla eget feugiat velit. Cras convallis suscipit lectus ut euismod. Sed pretium bibendum lectus eu rhoncus. Proin quis velit auctor, interdum mi id, suscipit nisi. Proin cursus leo scelerisque leo porta, at accumsan metus gravida. Vivamus ante orci, hendrerit id malesuada in, sodales ut lacus. Aliquam ut fermentum mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pharetra eleifend enim, vel commodo eros posuere nec.\n\nNunc sollicitudin enim viverra euismod placerat. Donec pulvinar, massa at consequat consequat, libero leo vehicula nibh, sit amet malesuada nulla magna quis sapien. Maecenas in nunc blandit, convallis elit vitae, eleifend lorem. Nullam placerat eget dolor lobortis tincidunt. Mauris ac sagittis dolor, ut vestibulum lorem. Vivamus tincidunt vitae risus ac rhoncus. Donec fermentum enim dictum gravida porta. Aenean bibendum auctor bibendum. Pellentesque eu eros rutrum, facilisis magna eu, blandit nunc. Etiam tincidunt purus nec leo pulvinar, quis dapibus ante adipiscing. Mauris eu justo erat.','2014-04-12 15:30:29',1);
INSERT INTO `blogarticle` (`blogID`,`articletitle`,`articletext`,`blogtime`,`blogposter`) VALUES (2,'Article Entry Number 2 Heading','Quisque sit amet scelerisque quam. Sed bibendum felis vitae urna mollis ullamcorper. Nunc non metus id augue pretium dignissim. Pellentesque interdum, tellus a imperdiet pharetra, nisl augue feugiat erat, et pretium tortor ligula non nunc. Vestibulum non erat et ligula euismod dictum ac eget urna. Praesent condimentum, eros ac pulvinar feugiat, ante arcu mattis arcu, et aliquet diam sem sit amet purus. Mauris at bibendum arcu.','2014-04-14 23:11:11',3);
INSERT INTO `blogarticle` (`blogID`,`articletitle`,`articletext`,`blogtime`,`blogposter`) VALUES (4,'Article Entry Number 4 Heading','Nulla placerat neque sed dapibus tristique. Nullam diam arcu, rhoncus non dui at, ultricies posuere velit. Integer eu ligula id tortor rhoncus condimentum non nec ligula. Pellentesque non facilisis neque. \r\nIn nec purus magna. Mauris libero lectus, ullamcorper sed nibh a, consectetur rhoncus urna. Nullam tristique tellus orci, quis convallis felis faucibus in. Duis tincidunt, nunc eu lobortis tristique, nibh neque dignissim dolor, in feugiat eros dolor sed nibh. Mauris fermentum leo non rutrum venenatis. Cras molestie orci sit amet massa gravida posuere. Nam sed metus elit. Fusce bibendum augue vel dui bibendum, eget elementum nunc rutrum. Quisque suscipit diam orci, nec adipiscing neque sollicitudin sit amet. Curabitur at orci eu dolor accumsan fringilla blandit non mauris.','2014-04-20 15:48:49',2);
